### ISSUE TITLE
Server sometimes returns error 52: code h

### ISSUE THREAD

**Issue by slimepharaoh** [slimepharaoh/MerchantX#1]
`{"error":52,"message":"Error while contacting server (code: h). Please try again."}`
I suppose this means that the hash value is incorrect, not quite sure though. A solution could be just sending the last request again, but it'd be better if we could get rid of this error.

**Comment by DigiFinaWiz** [comment]
You know sometimes the original game hangs on login, times out, etc, then I open MerchantX, it gets right in, then go back to original game and it works fine. Almost like MerchantX gives the server something different to think about, so when you go right back to original its now ready to connect.

**Comment by slimepharaoh** [comment]
fca07a13cc4ee136c0f8e5c8adc8c9eff5c6e6e8 probably fixed the problem by sending the request again.
